services:
  - type: web
    name: saving-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saving-7jm4
          property: connectionString
      - key: API_BASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEFAULT_PASSWORD
        value: Default@123
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: eu-west-1
      - key: S3_BUCKET
        value: saving-api-photos
